// <auto-generated />
using MVCcrudTurismo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCcrudTurismo.Migrations
{
    [DbContext(typeof(PassageiroContext))]
    [Migration("20220321171315_InicialCreate")]
    partial class InicialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCcrudTurismo.Models.Passageiro", b =>
                {
                    b.Property<int>("PassageiroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CpfPassageiro")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Destino")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("NomePassageiro")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Pagamento")
                        .HasColumnType("varchar(50)");

                    b.HasKey("PassageiroId");

                    b.ToTable("Passageiros");
                });
#pragma warning restore 612, 618
        }
    }
}
